# Generated by Django 6.0.5 on 2026-05-26 08:39

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('hospital', 'Hospital'), ('salon', 'Salon'), ('event', 'Event Management'), ('hotel', 'Hotel')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('hero_image', models.ImageField(blank=True, upload_to='heroes/')),
                ('brand_colors', models.JSONField(default=dict)),
                ('custom_css', models.TextField(blank=True)),
                ('working_hours', models.JSONField(default=dict)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('booking_lead_time', models.IntegerField(default=1)),
                ('max_booking_per_slot', models.IntegerField(default=1)),
                ('buffer_time', models.IntegerField(default=0)),
                ('stripe_account_id', models.CharField(blank=True, max_length=100)),
                ('google_calendar_enabled', models.BooleanField(default=False)),
                ('team_members', models.JSONField(default=list)),
                ('plan', models.CharField(default='free', max_length=20)),
                ('subscription_status', models.CharField(default='active', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('max_capacity', models.IntegerField(default=1)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='staff/')),
                ('availability', models.JSONField(default=dict)),
                ('services', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='businesses.business')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
