# Generated by Django 5.2.1 on 2026-06-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_platformsetting_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_type',
            field=models.CharField(blank=True, choices=[('salons', 'Salons and Beauty'), ('hospitals', 'Hospitals'), ('restaurants', 'Restaurant'), ('event-management', 'Event Management'), ('hotels', 'Hotels')], default='salons', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
