"""
Theme Registry for Bookify SaaS Platform.
Each business type has 5 distinct themes with full CSS variable definitions.
"""

THEME_REGISTRY = {
    'salon': {
        'rose_gold': {
            'label': 'Rose Gold Luxe',
            'description': 'Elegant rose gold tones for premium salons',
            'preview_color': '#c9a96e',
            'css_vars': {
                '--color-primary': '#c9a96e',
                '--color-secondary': '#8b6914',
                '--color-accent': '#f4d03f',
                '--color-bg': '#fdf6ec',
                '--color-surface': '#fff9f0',
                '--color-text': '#2c1810',
                '--color-text-muted': '#7a5c4a',
                '--color-border': '#e8d5b7',
                '--color-hero-overlay': 'rgba(201,169,110,0.55)',
                '--glass-bg': 'rgba(255,249,240,0.25)',
                '--glass-border': 'rgba(201,169,110,0.3)',
                '--border-radius': '16px',
                '--font-heading': "'Playfair Display', serif",
                '--font-body': "'Lato', sans-serif",
            },
        },
        'midnight_glam': {
            'label': 'Midnight Glam',
            'description': 'Dark, dramatic aesthetic for high-end salons',
            'preview_color': '#1a1a2e',
            'css_vars': {
                '--color-primary': '#e94560',
                '--color-secondary': '#0f3460',
                '--color-accent': '#e94560',
                '--color-bg': '#0d0d1a',
                '--color-surface': '#1a1a2e',
                '--color-text': '#eaeaea',
                '--color-text-muted': '#9a9ab0',
                '--color-border': '#2a2a4a',
                '--color-hero-overlay': 'rgba(13,13,26,0.65)',
                '--glass-bg': 'rgba(26,26,46,0.4)',
                '--glass-border': 'rgba(233,69,96,0.3)',
                '--border-radius': '12px',
                '--font-heading': "'Cormorant Garamond', serif",
                '--font-body': "'Raleway', sans-serif",
            },
        },
        'blush_minimal': {
            'label': 'Blush Minimal',
            'description': 'Clean, soft pink minimalist design',
            'preview_color': '#f8b4c8',
            'css_vars': {
                '--color-primary': '#e91e8c',
                '--color-secondary': '#f8b4c8',
                '--color-accent': '#ff6b9d',
                '--color-bg': '#fff5f8',
                '--color-surface': '#ffffff',
                '--color-text': '#2d1b2e',
                '--color-text-muted': '#9e6b7a',
                '--color-border': '#fce4ec',
                '--color-hero-overlay': 'rgba(233,30,140,0.4)',
                '--glass-bg': 'rgba(255,255,255,0.3)',
                '--glass-border': 'rgba(233,30,140,0.2)',
                '--border-radius': '24px',
                '--font-heading': "'Josefin Sans', sans-serif",
                '--font-body': "'Nunito', sans-serif",
            },
        },
        'forest_spa': {
            'label': 'Forest Spa',
            'description': 'Natural, earthy tones for organic salons',
            'preview_color': '#2d6a4f',
            'css_vars': {
                '--color-primary': '#2d6a4f',
                '--color-secondary': '#52b788',
                '--color-accent': '#95d5b2',
                '--color-bg': '#f0f7f4',
                '--color-surface': '#ffffff',
                '--color-text': '#1b3a2d',
                '--color-text-muted': '#5a7a6a',
                '--color-border': '#d8ede5',
                '--color-hero-overlay': 'rgba(45,106,79,0.5)',
                '--glass-bg': 'rgba(240,247,244,0.3)',
                '--glass-border': 'rgba(82,183,136,0.3)',
                '--border-radius': '12px',
                '--font-heading': "'Merriweather', serif",
                '--font-body': "'Source Sans Pro', sans-serif",
            },
        },
        'urban_chic': {
            'label': 'Urban Chic',
            'description': 'Bold, modern urban style',
            'preview_color': '#212121',
            'css_vars': {
                '--color-primary': '#ff5722',
                '--color-secondary': '#212121',
                '--color-accent': '#ffc107',
                '--color-bg': '#f5f5f5',
                '--color-surface': '#ffffff',
                '--color-text': '#212121',
                '--color-text-muted': '#757575',
                '--color-border': '#e0e0e0',
                '--color-hero-overlay': 'rgba(33,33,33,0.6)',
                '--glass-bg': 'rgba(255,255,255,0.2)',
                '--glass-border': 'rgba(255,87,34,0.3)',
                '--border-radius': '4px',
                '--font-heading': "'Bebas Neue', cursive",
                '--font-body': "'Inter', sans-serif",
            },
        },
    },

    'restaurant': {
        'bistro_warm': {
            'label': 'Bistro Warm',
            'description': 'Warm, inviting tones for cozy restaurants',
            'preview_color': '#c0392b',
            'css_vars': {
                '--color-primary': '#c0392b',
                '--color-secondary': '#e67e22',
                '--color-accent': '#f39c12',
                '--color-bg': '#fdf5e6',
                '--color-surface': '#fff8f0',
                '--color-text': '#2c1810',
                '--color-text-muted': '#7a5c4a',
                '--color-border': '#f0d9c0',
                '--color-hero-overlay': 'rgba(192,57,43,0.5)',
                '--glass-bg': 'rgba(255,248,240,0.3)',
                '--glass-border': 'rgba(192,57,43,0.25)',
                '--border-radius': '8px',
                '--font-heading': "'Playfair Display', serif",
                '--font-body': "'Lora', serif",
            },
        },
        'fine_dining': {
            'label': 'Fine Dining',
            'description': 'Sophisticated dark theme for upscale restaurants',
            'preview_color': '#1c1c1c',
            'css_vars': {
                '--color-primary': '#d4af37',
                '--color-secondary': '#1c1c1c',
                '--color-accent': '#c9a96e',
                '--color-bg': '#0a0a0a',
                '--color-surface': '#1c1c1c',
                '--color-text': '#f5f5f0',
                '--color-text-muted': '#a0a090',
                '--color-border': '#2a2a2a',
                '--color-hero-overlay': 'rgba(10,10,10,0.7)',
                '--glass-bg': 'rgba(28,28,28,0.5)',
                '--glass-border': 'rgba(212,175,55,0.3)',
                '--border-radius': '2px',
                '--font-heading': "'Cormorant Garamond', serif",
                '--font-body': "'EB Garamond', serif",
            },
        },
        'fresh_garden': {
            'label': 'Fresh Garden',
            'description': 'Light, fresh theme for farm-to-table restaurants',
            'preview_color': '#27ae60',
            'css_vars': {
                '--color-primary': '#27ae60',
                '--color-secondary': '#2ecc71',
                '--color-accent': '#f1c40f',
                '--color-bg': '#f0faf4',
                '--color-surface': '#ffffff',
                '--color-text': '#1a3a2a',
                '--color-text-muted': '#5a8a6a',
                '--color-border': '#c8e6c9',
                '--color-hero-overlay': 'rgba(39,174,96,0.45)',
                '--glass-bg': 'rgba(240,250,244,0.35)',
                '--glass-border': 'rgba(39,174,96,0.25)',
                '--border-radius': '16px',
                '--font-heading': "'Nunito', sans-serif",
                '--font-body': "'Open Sans', sans-serif",
            },
        },
        'street_food': {
            'label': 'Street Food',
            'description': 'Vibrant, energetic theme for casual eateries',
            'preview_color': '#ff6b35',
            'css_vars': {
                '--color-primary': '#ff6b35',
                '--color-secondary': '#f7c59f',
                '--color-accent': '#efefd0',
                '--color-bg': '#1a1a1a',
                '--color-surface': '#2a2a2a',
                '--color-text': '#ffffff',
                '--color-text-muted': '#cccccc',
                '--color-border': '#3a3a3a',
                '--color-hero-overlay': 'rgba(26,26,26,0.6)',
                '--glass-bg': 'rgba(42,42,42,0.4)',
                '--glass-border': 'rgba(255,107,53,0.3)',
                '--border-radius': '8px',
                '--font-heading': "'Fredoka One', cursive",
                '--font-body': "'Poppins', sans-serif",
            },
        },
        'mediterranean': {
            'label': 'Mediterranean',
            'description': 'Blue and white coastal Mediterranean style',
            'preview_color': '#1565c0',
            'css_vars': {
                '--color-primary': '#1565c0',
                '--color-secondary': '#42a5f5',
                '--color-accent': '#ffb300',
                '--color-bg': '#f0f8ff',
                '--color-surface': '#ffffff',
                '--color-text': '#0d2137',
                '--color-text-muted': '#5a7a9a',
                '--color-border': '#bbdefb',
                '--color-hero-overlay': 'rgba(21,101,192,0.45)',
                '--glass-bg': 'rgba(240,248,255,0.35)',
                '--glass-border': 'rgba(21,101,192,0.25)',
                '--border-radius': '12px',
                '--font-heading': "'Cinzel', serif",
                '--font-body': "'Raleway', sans-serif",
            },
        },
    },

    'hospital': {
        'clinical_blue': {
            'label': 'Clinical Blue',
            'description': 'Professional, trustworthy medical blue',
            'preview_color': '#1565c0',
            'css_vars': {
                '--color-primary': '#1565c0',
                '--color-secondary': '#42a5f5',
                '--color-accent': '#00acc1',
                '--color-bg': '#f5f9ff',
                '--color-surface': '#ffffff',
                '--color-text': '#0d2137',
                '--color-text-muted': '#546e7a',
                '--color-border': '#e3f2fd',
                '--color-hero-overlay': 'rgba(21,101,192,0.5)',
                '--glass-bg': 'rgba(245,249,255,0.35)',
                '--glass-border': 'rgba(21,101,192,0.2)',
                '--border-radius': '8px',
                '--font-heading': "'Roboto', sans-serif",
                '--font-body': "'Open Sans', sans-serif",
            },
        },
        'healing_green': {
            'label': 'Healing Green',
            'description': 'Calming green tones for wellness clinics',
            'preview_color': '#00695c',
            'css_vars': {
                '--color-primary': '#00695c',
                '--color-secondary': '#26a69a',
                '--color-accent': '#80cbc4',
                '--color-bg': '#f0faf8',
                '--color-surface': '#ffffff',
                '--color-text': '#00251a',
                '--color-text-muted': '#4a7a70',
                '--color-border': '#b2dfdb',
                '--color-hero-overlay': 'rgba(0,105,92,0.5)',
                '--glass-bg': 'rgba(240,250,248,0.35)',
                '--glass-border': 'rgba(0,105,92,0.2)',
                '--border-radius': '12px',
                '--font-heading': "'Nunito', sans-serif",
                '--font-body': "'Source Sans Pro', sans-serif",
            },
        },
        'pure_white': {
            'label': 'Pure White',
            'description': 'Ultra-clean minimal white for modern clinics',
            'preview_color': '#2196f3',
            'css_vars': {
                '--color-primary': '#2196f3',
                '--color-secondary': '#e3f2fd',
                '--color-accent': '#ff5722',
                '--color-bg': '#fafafa',
                '--color-surface': '#ffffff',
                '--color-text': '#212121',
                '--color-text-muted': '#757575',
                '--color-border': '#eeeeee',
                '--color-hero-overlay': 'rgba(33,150,243,0.4)',
                '--glass-bg': 'rgba(255,255,255,0.4)',
                '--glass-border': 'rgba(33,150,243,0.2)',
                '--border-radius': '4px',
                '--font-heading': "'Inter', sans-serif",
                '--font-body': "'Inter', sans-serif",
            },
        },
        'warm_care': {
            'label': 'Warm Care',
            'description': 'Warm, approachable tones for family clinics',
            'preview_color': '#e65100',
            'css_vars': {
                '--color-primary': '#e65100',
                '--color-secondary': '#ff8a65',
                '--color-accent': '#ffcc02',
                '--color-bg': '#fff8f5',
                '--color-surface': '#ffffff',
                '--color-text': '#2c1810',
                '--color-text-muted': '#8d6e63',
                '--color-border': '#ffe0d0',
                '--color-hero-overlay': 'rgba(230,81,0,0.45)',
                '--glass-bg': 'rgba(255,248,245,0.35)',
                '--glass-border': 'rgba(230,81,0,0.2)',
                '--border-radius': '16px',
                '--font-heading': "'Poppins', sans-serif",
                '--font-body': "'Lato', sans-serif",
            },
        },
        'night_shift': {
            'label': 'Night Shift',
            'description': 'Dark professional theme for 24/7 facilities',
            'preview_color': '#0d47a1',
            'css_vars': {
                '--color-primary': '#448aff',
                '--color-secondary': '#0d47a1',
                '--color-accent': '#00e5ff',
                '--color-bg': '#0a0e1a',
                '--color-surface': '#111827',
                '--color-text': '#e8eaf6',
                '--color-text-muted': '#7986cb',
                '--color-border': '#1e2a4a',
                '--color-hero-overlay': 'rgba(10,14,26,0.7)',
                '--glass-bg': 'rgba(17,24,39,0.5)',
                '--glass-border': 'rgba(68,138,255,0.25)',
                '--border-radius': '8px',
                '--font-heading': "'Exo 2', sans-serif",
                '--font-body': "'Roboto', sans-serif",
            },
        },
    },

    'hotel': {
        'grand_luxury': {
            'label': 'Grand Luxury',
            'description': 'Classic gold and navy for 5-star hotels',
            'preview_color': '#1a237e',
            'css_vars': {
                '--color-primary': '#d4af37',
                '--color-secondary': '#1a237e',
                '--color-accent': '#c9a96e',
                '--color-bg': '#fafaf5',
                '--color-surface': '#ffffff',
                '--color-text': '#1a1a2e',
                '--color-text-muted': '#6a6a8a',
                '--color-border': '#e8e0c8',
                '--color-hero-overlay': 'rgba(26,35,126,0.55)',
                '--glass-bg': 'rgba(255,255,255,0.2)',
                '--glass-border': 'rgba(212,175,55,0.35)',
                '--border-radius': '4px',
                '--font-heading': "'Cormorant Garamond', serif",
                '--font-body': "'Libre Baskerville', serif",
            },
        },
        'boutique_modern': {
            'label': 'Boutique Modern',
            'description': 'Contemporary minimalist boutique hotel style',
            'preview_color': '#37474f',
            'css_vars': {
                '--color-primary': '#37474f',
                '--color-secondary': '#78909c',
                '--color-accent': '#ff7043',
                '--color-bg': '#f8f9fa',
                '--color-surface': '#ffffff',
                '--color-text': '#212121',
                '--color-text-muted': '#757575',
                '--color-border': '#eceff1',
                '--color-hero-overlay': 'rgba(55,71,79,0.55)',
                '--glass-bg': 'rgba(248,249,250,0.3)',
                '--glass-border': 'rgba(55,71,79,0.2)',
                '--border-radius': '2px',
                '--font-heading': "'Montserrat', sans-serif",
                '--font-body': "'Lato', sans-serif",
            },
        },
        'tropical_resort': {
            'label': 'Tropical Resort',
            'description': 'Vibrant tropical colors for beach resorts',
            'preview_color': '#00838f',
            'css_vars': {
                '--color-primary': '#00838f',
                '--color-secondary': '#26c6da',
                '--color-accent': '#ffca28',
                '--color-bg': '#e0f7fa',
                '--color-surface': '#ffffff',
                '--color-text': '#00363a',
                '--color-text-muted': '#4a8a90',
                '--color-border': '#b2ebf2',
                '--color-hero-overlay': 'rgba(0,131,143,0.45)',
                '--glass-bg': 'rgba(224,247,250,0.35)',
                '--glass-border': 'rgba(0,131,143,0.25)',
                '--border-radius': '20px',
                '--font-heading': "'Pacifico', cursive",
                '--font-body': "'Nunito', sans-serif",
            },
        },
        'mountain_lodge': {
            'label': 'Mountain Lodge',
            'description': 'Rustic warm tones for mountain retreats',
            'preview_color': '#4e342e',
            'css_vars': {
                '--color-primary': '#4e342e',
                '--color-secondary': '#8d6e63',
                '--color-accent': '#ff8f00',
                '--color-bg': '#fdf3e7',
                '--color-surface': '#fff8f0',
                '--color-text': '#2c1810',
                '--color-text-muted': '#7a5c4a',
                '--color-border': '#e8d5b7',
                '--color-hero-overlay': 'rgba(78,52,46,0.6)',
                '--glass-bg': 'rgba(253,243,231,0.3)',
                '--glass-border': 'rgba(78,52,46,0.25)',
                '--border-radius': '8px',
                '--font-heading': "'Abril Fatface', cursive",
                '--font-body': "'Merriweather', serif",
            },
        },
        'urban_suite': {
            'label': 'Urban Suite',
            'description': 'Sleek dark theme for city business hotels',
            'preview_color': '#212121',
            'css_vars': {
                '--color-primary': '#9c27b0',
                '--color-secondary': '#212121',
                '--color-accent': '#e040fb',
                '--color-bg': '#121212',
                '--color-surface': '#1e1e1e',
                '--color-text': '#ffffff',
                '--color-text-muted': '#aaaaaa',
                '--color-border': '#2a2a2a',
                '--color-hero-overlay': 'rgba(18,18,18,0.65)',
                '--glass-bg': 'rgba(30,30,30,0.45)',
                '--glass-border': 'rgba(156,39,176,0.3)',
                '--border-radius': '0px',
                '--font-heading': "'Rajdhani', sans-serif",
                '--font-body': "'Roboto', sans-serif",
            },
        },
    },

    'event': {
        'festival_bright': {
            'label': 'Festival Bright',
            'description': 'Bold, colorful theme for festivals and concerts',
            'preview_color': '#6a1b9a',
            'css_vars': {
                '--color-primary': '#6a1b9a',
                '--color-secondary': '#e91e63',
                '--color-accent': '#ffeb3b',
                '--color-bg': '#0d0d1a',
                '--color-surface': '#1a1a2e',
                '--color-text': '#ffffff',
                '--color-text-muted': '#cccccc',
                '--color-border': '#2a2a4a',
                '--color-hero-overlay': 'rgba(13,13,26,0.6)',
                '--glass-bg': 'rgba(26,26,46,0.4)',
                '--glass-border': 'rgba(106,27,154,0.4)',
                '--border-radius': '12px',
                '--font-heading': "'Bungee', cursive",
                '--font-body': "'Poppins', sans-serif",
            },
        },
        'corporate_event': {
            'label': 'Corporate Event',
            'description': 'Professional theme for business conferences',
            'preview_color': '#1565c0',
            'css_vars': {
                '--color-primary': '#1565c0',
                '--color-secondary': '#0d47a1',
                '--color-accent': '#ff6f00',
                '--color-bg': '#f5f7fa',
                '--color-surface': '#ffffff',
                '--color-text': '#1a2332',
                '--color-text-muted': '#546e7a',
                '--color-border': '#e0e8f0',
                '--color-hero-overlay': 'rgba(21,101,192,0.55)',
                '--glass-bg': 'rgba(245,247,250,0.35)',
                '--glass-border': 'rgba(21,101,192,0.2)',
                '--border-radius': '4px',
                '--font-heading': "'Montserrat', sans-serif",
                '--font-body': "'Open Sans', sans-serif",
            },
        },
        'wedding_elegant': {
            'label': 'Wedding Elegant',
            'description': 'Romantic, soft theme for weddings and galas',
            'preview_color': '#ad1457',
            'css_vars': {
                '--color-primary': '#ad1457',
                '--color-secondary': '#f8bbd0',
                '--color-accent': '#d4af37',
                '--color-bg': '#fff5f8',
                '--color-surface': '#ffffff',
                '--color-text': '#2d1b2e',
                '--color-text-muted': '#9e6b7a',
                '--color-border': '#fce4ec',
                '--color-hero-overlay': 'rgba(173,20,87,0.4)',
                '--glass-bg': 'rgba(255,255,255,0.35)',
                '--glass-border': 'rgba(173,20,87,0.2)',
                '--border-radius': '20px',
                '--font-heading': "'Great Vibes', cursive",
                '--font-body': "'Lato', sans-serif",
            },
        },
        'sports_arena': {
            'label': 'Sports Arena',
            'description': 'High-energy theme for sports events',
            'preview_color': '#e53935',
            'css_vars': {
                '--color-primary': '#e53935',
                '--color-secondary': '#212121',
                '--color-accent': '#fdd835',
                '--color-bg': '#0a0a0a',
                '--color-surface': '#1a1a1a',
                '--color-text': '#ffffff',
                '--color-text-muted': '#aaaaaa',
                '--color-border': '#2a2a2a',
                '--color-hero-overlay': 'rgba(10,10,10,0.65)',
                '--glass-bg': 'rgba(26,26,26,0.45)',
                '--glass-border': 'rgba(229,57,53,0.35)',
                '--border-radius': '4px',
                '--font-heading': "'Oswald', sans-serif",
                '--font-body': "'Roboto Condensed', sans-serif",
            },
        },
        'art_gallery': {
            'label': 'Art Gallery',
            'description': 'Minimalist white theme for art exhibitions',
            'preview_color': '#212121',
            'css_vars': {
                '--color-primary': '#212121',
                '--color-secondary': '#757575',
                '--color-accent': '#ff5722',
                '--color-bg': '#ffffff',
                '--color-surface': '#fafafa',
                '--color-text': '#212121',
                '--color-text-muted': '#757575',
                '--color-border': '#e0e0e0',
                '--color-hero-overlay': 'rgba(33,33,33,0.5)',
                '--glass-bg': 'rgba(255,255,255,0.4)',
                '--glass-border': 'rgba(33,33,33,0.15)',
                '--border-radius': '0px',
                '--font-heading': "'Didact Gothic', sans-serif",
                '--font-body': "'Karla', sans-serif",
            },
        },
    },
}


def get_themes_for_type(business_type):
    """Return list of (key, theme_data) for a given business type."""
    return list(THEME_REGISTRY.get(business_type, {}).items())


def get_theme(business_type, theme_key):
    """Return a single theme dict or the first available theme."""
    themes = THEME_REGISTRY.get(business_type, {})
    if theme_key in themes:
        return themes[theme_key]
    if themes:
        return next(iter(themes.values()))
    return {}


def render_css_vars(business):
    """Generate inline CSS variable block for a business's active theme."""
    if not business:
        return ''
    theme_data = get_theme(business.business_type, business.theme)
    css_vars = theme_data.get('css_vars', {})

    # Allow business to override individual colors
    brand = business.brand_colors or {}
    if brand.get('primary'):
        css_vars['--color-primary'] = brand['primary']
    if brand.get('secondary'):
        css_vars['--color-secondary'] = brand['secondary']
    if brand.get('accent'):
        css_vars['--color-accent'] = brand['accent']

    lines = '\n'.join(f'    {k}: {v};' for k, v in css_vars.items())
    return f':root {{\n{lines}\n}}'
