# Generated by Django 6.0.5 on 2026-05-26 08:39

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('customer_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='website', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.service')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.staff')),
            ],
            options={
                'db_table': 'bookings',
                'indexes': [models.Index(fields=['business', 'date'], name='bookings_busines_d77581_idx'), models.Index(fields=['business', 'customer_email'], name='bookings_busines_ce3697_idx')],
            },
        ),
    ]
