# Generated by Django 5.2.1 on 2026-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_id',
            field=models.CharField(blank=True, editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('offline_pending', 'Offline - Pending')], default='unpaid', max_length=20),
        ),
    ]
