# Generated by Django 5.2.1 on 2026-07-12 18:10

from django.db import migrations
import random


def generate_client_id():
    """Generate a unique 6-digit client ID."""
    return f"{random.randint(100000, 999999)}"


def populate_client_ids(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    
    # Get all bookings without client_id
    bookings = Booking.objects.filter(client_id='')
    
    for booking in bookings:
        client_id = generate_client_id()
        # Ensure uniqueness
        while Booking.objects.filter(client_id=client_id).exists():
            client_id = generate_client_id()
        booking.client_id = client_id
        booking.save(update_fields=['client_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_client_id_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_client_ids, reverse_code=migrations.RunPython.noop),
    ]
