# Generated by Django 5.2.1 on 2026-07-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_populate_client_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_id'], name='bookings_client_id_idx'),
        ),
    ]
