# Generated by Django 5.2.1 on 2026-07-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_client_id_unique'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_client_id_idx',
        ),
    ]
